"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "${custom.shortpath} $character"
right_format = """${custom.git_branch_custom}$all"""

command_timeout = 5000

[directory]
disabled = true

[custom.shortpath]
command = "jumpr shortpath --section full $PWD"
when = "true"
format = "[$output]($style)"
style = "cyan"
description = "Shortened path from jumpr"

[username]
disabled = true

[hostname]
disabled = true

[gcloud]
disabled = true

[container]
disabled = true

[git_status]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
disabled = true

# Temporary workaround until reftable support added
[custom.git_branch_custom]
command = "git symbolic-ref --short HEAD"
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
format = "[$symbol$output]($style) "
symbol = " "
style = "bold purple"
