"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """$directory$character"""
right_format = """$all"""

command_timeout = 1000

[directory]
repo_root_format = '[](purple)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
fish_style_pwd_dir_length = 1
repo_root_style = "bold cyan"
truncate_to_repo = true
truncation_length = 10

[status]
disabled = false

[username]
disabled = true

[hostname]
disabled = true

[gcloud]
disabled = true

[container]
disabled = true

[git_status]
# git is too slow on the repos I use..
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
