"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "${env_var.WORKTREE_PATH_PREFIX}${env_var.WORKTREE_PATH_SHORTENED}${env_var.WORKTREE_PATH_NORMAL} $character"
right_format = """$all"""

command_timeout = 5000

[directory]
disabled = true

[env_var.WORKTREE_PATH_PREFIX]
default = ""
format = "[$env_value]($style)"
style = "purple"
description = "Path prefix from worktree-util"

[env_var.WORKTREE_PATH_SHORTENED]
default = ""
format = "[$env_value]($style)"
style = "cyan"
description = "Shortened path segments from worktree-util"

[env_var.WORKTREE_PATH_NORMAL]
default = ""
format = "[$env_value]($style)"
style = "bold cyan"
description = "Full path segments from worktree-util"

[username]
disabled = true

[hostname]
disabled = true

[gcloud]
disabled = true

[container]
disabled = true

[git_status]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
