"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "${env_var.STARSHIP_PATH_PREFIX}${env_var.STARSHIP_PATH_SHORTENED}${env_var.STARSHIP_PATH_NORMAL}$character"
right_format = """$all"""

command_timeout = 5000

[directory]
disabled = true
repo_root_format = '[](purple)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
fish_style_pwd_dir_length = 1
repo_root_style = "bold cyan"
truncate_to_repo = true
truncation_length = 10

[env_var.STARSHIP_PATH_PREFIX]
format = "[$env_value]($style)"
style = "purple"
description = "Path prefix"

[env_var.STARSHIP_PATH_SHORTENED]
format = "[$env_value]($style)"
style = "cyan"
description = "Shortened path segments"

[env_var.STARSHIP_PATH_NORMAL]
format = "[$env_value]($style) "
style = "bold cyan"
description = "Full path segments"

[username]
disabled = true

[hostname]
disabled = true

[gcloud]
disabled = true

[container]
disabled = true

[git_status]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
