#!/usr/bin/env zsh

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

export SHELL="$(which zsh)"

if [[ -z "$IS_WINDOWS" ]]
then
    export IS_WINDOWS=$(
        [[ "$(uname -r)" =~ "([Mm]icrosoft|[Ww]indows)" ]] \
        && echo 'true' \
        || echo 'false'
    )
fi
if [[ -z "$IS_MACOS" ]]
then
    export IS_MACOS=$([[ "$(uname -s)" == "Darwin" ]] \
        && echo 'true' \
        || echo 'false'
    )
fi

export DISABLE_AUTO_UPDATE=true

# this should compile/recompile all the files here..
# runs threaded, because it's really slow :)
#(
#    autoload -U zrecompile
#
#    for f in ~/.zshrc $zsh_cache/* $HOME/.zsh/conf.d/*
#    do
#        echo "$f" | grep -qv "\.zwc$" &&
#        zrecompile -p $f >> /dev/null && rm -f $f.zwc.old
#    done &
#) &> /dev/null
