#!/usr/bin/env zsh

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Let me know my shell!
echo Zsh
export SHELL="`which zsh`"

# this should compile/recompile all the files here..
# runs threaded, because it's really slow :)
#(
#    autoload -U zrecompile
#
#    for f in ~/.zshrc $zsh_cache/* $HOME/.zsh/conf.d/*
#    do
#        echo "$f" | grep -qv "\.zwc$" &&
#        zrecompile -p $f >> /dev/null && rm -f $f.zwc.old
#    done &
#) &> /dev/null
