#!/bin/zsh

export ADOTDIR="$HOME/.zsh/bundle"

logTime "start bundles"

antigen use oh-my-zsh
logTime "did use"

# zsh plugins
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search

# python stuff
antigen bundle pip
which virtualenvwrapper_lazy.sh &>/dev/null \
    && antigen bundle virtualenvwrapper
#antigen bundle pep8
antigen bundle django
antigen bundle fabric

# android/java stuff
antigen bundle ant
antigen bundle gradle

# general stuff
antigen bundle brew
antigen bundle vagrant

logTime "did bundles"

function antigen-selfupdate {
    curl https://raw.github.com/zsh-users/antigen/master/antigen.zsh > $HOME/.zsh/conf.d/S02-antigen
    source $HOME/.zsh/conf.d/S02-antigen
    antigen update
    antigen cleanup
}
