#!/bin/zsh

if [[ -e ~/.zplug/init.zsh ]]
then
    export ZPLUG_HOME=$HOME/.zplug
elif [[ -e /usr/local/opt/zplug/init.zsh ]]
then
    export ZPLUG_HOME=/usr/local/opt/zplug
fi

if [[ -z "$ZPLUG_HOME" ]]
then
    echo "Zplug is not installed!"
    return
fi

source $ZPLUG_HOME/init.zsh

# zsh plugins
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-history-substring-search"
#zplug djui/alias-tips
zplug 'zplug/zplug', hook-build:'zplug --self-manage'
#zplug marzocchi/zsh-notify, at:next-iterm

# python stuff
#zplug plugins/pip, from:oh-my-zsh, if:"which pip"
#zplug plugins/django, from:oh-my-zsh
#zplug plugins/virtualenvwrapper, from:oh-my-zsh, if:"which virtualenvwrapper_lazy.sh"

# general stuff
#zplug plugins/brew, from:oh-my-zsh
#zplug plugins/vagrant, from:oh-my-zsh
