#!/bin/zsh

autoload -U zrecompile

function _loadBundle() {
    local file="$HOME/.zsh/bundles/${1}" 

    if [[ ! -f "${file}" ]] 
    then
        echo "not loading ${1}" 1>&2
        return
    fi

    #zrecompile -p "${file}"
    source "${file}"
    logTime "loaded bundle ${1}"
}


_loadBundle zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
_loadBundle zsh-history-substring-search/zsh-history-substring-search.zsh
