#!/usr/bin/env zsh

ZHOST=`hostname`

# deal with stupid hostnames
if [[ "$ZHOST" == "razz" ]]; then
    :
elif [[ "$ZHOST" == "jazz" ]]; then
    :
elif [[ $ZHOST =~ ".vagrant." ]] || [[ $ZHOST == "mysql1" ]] || [[ $ZHOST == "www1" ]]; then
    ZHOST="$(echo $ZHOST | sed 's/\(.*\)\.vagrant\..*/vagrant-\1/')"
elif [[ $ZHOST =~ "vm-test-" ]]; then
    ZHOST="$(echo $ZHOST | sed 's/\(vm-test[^.]*\)\..*/\1/')"
elif [[ $ZHOST =~ "Ryans-MacBook-Pro" || $ZHOST =~ "aio-tv.com" ]]; then
    ZHOST="work"
fi

export ZHOST
