#!/usr/bin/env zsh

ZHOST=`hostname`

# deal with stupid hostnames
if [[ "$ZHOST" == "razz" ]]; then
    :
elif [[ "$ZHOST" == "jazz" ]]; then
    :
elif [[ $ZHOST == "cherokee" ]]; then
    :
elif [[ $ZHOST =~ "linode" ]]; then
    ZHOST="linode"
elif [[ $ZHOST =~ "acadiau\.ca" ]]; then
    ZHOST="acadia"
elif [[ $ZHOST =~ "CI000" ]]; then
    ZHOST="work"
elif [[ $ZHOST =~ "Ryans-MacBook-Pro" || $ZHOST =~ "aio-tv.com" ]]; then
    ZHOST="work"
elif [[ $ZHOST =~ "vm-test-" ]]; then
    ZHOST="$(echo $ZHOST | sed 's/\(vm-test[^.]*\)\..*/\1/')"
elif [[ $ZHOST =~ ".vagrant." ]]; then
    ZHOST="$(echo $ZHOST | sed 's/\(.*\)\.vagrant\..*/vagrant-\1/')"
else
    #ZHOST="other"
fi

export ZHOST
