#!/usr/bin/env zsh

######## Set/unset  shell options ###############
# See http://zsh.sunsite.dk/Doc/Release/Options.html

if which gdircolors &> /dev/null || which dircolors &> /dev/null; then
    if which gdircolors &> /dev/null ; then
        eval "`gdircolors`"
    elif which dircolors &> /dev/null; then
        eval "`dircolors`"
    fi
    export LS_COLORS="*.ogm=01;35:${LS_COLORS}"
    export ZLS_COLORS=$LS_COLORS
fi


# Job control
setopt no_bg_nice           # don't renice jobs in bg
setopt no_hup               # don't SIGHUP bg cmds on logout
setopt long_list_jobs       # list jobs in long format
setopt notify               # notify immediately, not on next prompt
setopt check_jobs           # check jobs on exit
setopt monitor              # job control


# pushd
setopt auto_pushd           # cd = pushd
setopt pushd_ignore_dups    # ignore dups in pushd
setopt pushd_silent         # don't print stack after push/pop
setopt pushd_to_home        # pushd == pushd $HOME

# completion
setopt aliases              # expand aliases
setopt always_to_end        # always go to end of word after completion
setopt auto_list            # list choice on ambiguous command
setopt auto_menu            # show menu for completion
setopt auto_remove_slash    # remove slash on dirs if word separator added
setopt bad_pattern          # warn on bad file patterns
setopt case_glob            # case sensitive globbing
setopt correct              # try to correct command line
#setopt no_correct_all       # don't coorect args
setopt equals               # perform = file expansions
setopt no_rec_exact         # recognize exact match even if ambiguous
setopt no_rm_star_silent    # ask user before rm foo/*
setopt nonomatch            # avoid the 'zsh: no matches found...'
unsetopt auto_param_slash   # add slash for directories



# removed recexact

# history
setopt append_history       # append to history, dont truncate it
setopt bang_hist            # yeah ! expansion
setopt hist_verify          # expand !, but don't call immediately
setopt hist_allow_clobber   # add | to redirections in history
setopt hist_find_no_dups    # don't show dups even if not contiguous
setopt hist_ignore_all_dups # ignore all -- even non contiguous -- dups
setopt hist_save_no_dups    # no dups on history saving
setopt inc_appendhistory    # append incrementally
setopt share_history        # traditional bash-history
setopt no_extended_history  # regular history


# other
setopt no_mail_warning      # auto-explained
setopt rc_quotes            # '' == ' in 'quoted exprs
setopt extended_glob        # #,~,^ expansion
setopt clobber              # redirection can create files
setopt no_emacs             # use rather bindkeys that builtin
#setopt err_exit             # see exit status if nonzero
setopt no_flow_control      # ignore ^S/^Q
setopt no_ignore_eof        # don't ignore ^D
setopt interactive_comments # allow comments in interactive shell
setopt multios              # multi redirection allowed
setopt no_single_line_zle   # use multiline editor
setopt no_sun_keyboard_hack # i don't use sun kb
setopt vi                   # use bindkeys
#setopt no_xtrace            # do not debug by default
setopt zle                  # use zsh le
setopt prompt_subst         # allow substitutions in prompts


# removed opts
# globdots cdablevars autoresume pushdminus 


########### modules ####################

# Autoload zsh modules when they are referenced
zmodload -a zsh/stat stat
zmodload -a zsh/zpty zpty
zmodload -a zsh/zprof zprof
zmodload -ap zsh/mapfile mapfile


# http://xanana.ucsc.edu/~wgscott/wordpress_new/wordpress/?p=12
# Use an array of functions for these instead of a single function
typeset -ga preexec_functions
typeset -ga precmd_functions
typeset -ga chpwd_functions

## Aliasing "run-help"
#unalias run-help
autoload run-help


