#!/usr/bin/env zsh

[[ -z "$HOME" ]] && export HOME=$(cd ~ ; pwd)
[[ -z "$HOSTNAME" ]] && export HOSTNAME=$(hostname)

export EMAIL="rygwdn@gmail.com"
export FULLNAME="Ryan Wooden"
export TZ="America/Halifax"

[[ -z $CYGWIN ]] && export CYGWIN=nodosfilewarning

export HISTSIZE=10000              # size of history
export SAVEHIST=10000              # maximum of history events to be save
export LISTMAX=1000                # never ask
export LOGCHECK=60
export HISTFILE=$HOME/.zhistory

export NULLCMD='less'               # use cat for > null commands
export REPORTTIME=10                # report time if execution exceeds amount of seconds
watch=(notme)                # watch login/logout

# Set up less
export PAGER='less'
# show colors in less
export LESS="-R"
# syntax highlight files from less
#which pygmentize &>/dev/null && export LESSOPEN='|pygmentize -g %s'

export EDITOR='vim'
export VISUAL='vim'
export VPAGER='vim -R -'

# Set up color vars
autoload colors zsh/terminfo

if [[ "$terminfo[colors]" -ge 8 ]]
then
    colors
    for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE
    do
        eval export PR_$color='%{$terminfo[bold]$fg[${(L)color}]%}'
        eval export PR_LIGHT_$color='%{$fg[${(L)color}]%}'
        (( count = $count + 1 ))
    done
    export PR_NO_COLOR="%{$terminfo[sgr0]%}"
fi

# Enable colors in grep
#export GREP_OPTIONS="--color=auto"

# local stuff
export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'
export LC_CTYPE='C'

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# these are the default arguments to exuberant-ctags
export CTAGS="--c++-kinds=+p --fields=+iaS --extra=+q"

if [[ -n "$SSH_TTY" ]]
then
    export PULSE_SERVER="tcp:`echo $SSH_CLIENT | sed 's/ .*//'`:4713 ssh"
fi

if [[ -d /vagrant || $ZHOST =~ "vm-test" ]]
then
    # only use "light" vim bundles on vagrant
    export VIM_LIGHT_BUNDLES=1
fi
