#!/usr/bin/env zsh

#######################################################################
#                      Set up keys from terminfo                      #
#######################################################################

zmodload zsh/terminfo

typeset -A key

key[Home]=${terminfo[khome]}
key[End]=${terminfo[kend]}
key[Insert]=${terminfo[kich1]}
key[Delete]=${terminfo[kdch1]}
key[Backspace]=${terminfo[kbs]}
key[Up]=${terminfo[kcuu1]}
key[Down]=${terminfo[kcud1]}
key[Left]=${terminfo[kcub1]}
key[Right]=${terminfo[kcuf1]}
key[PageUp]=${terminfo[kpp]}
key[PageDown]=${terminfo[knp]}

# Finally, make sure the terminal is in application mode, when zle is
# active. Only then are the values from $terminfo valid.
if (( ${+terminfo[smkx]} )) && (( ${+terminfo[rmkx]} )); then
    function zle-line-init () {
        printf '%s' "${terminfo[smkx]}"
    }
    function zle-line-finish () {
        printf '%s' "${terminfo[rmkx]}"
    }
    zle -N zle-line-init
    zle -N zle-line-finish
fi


#######################################################################
#                            fix some keys                            #
#######################################################################

[[ -n "${key[Home]}"      ]]  && bindkey  "${key[Home]}"      beginning-of-line
[[ -n "${key[End]}"       ]]  && bindkey  "${key[End]}"       end-of-line
[[ -n "${key[Insert]}"    ]]  && bindkey  "${key[Insert]}"    overwrite-mode
[[ -n "${key[Delete]}"    ]]  && bindkey  "${key[Delete]}"    delete-char
[[ -n "${key[Backspace]}" ]]  && bindkey  "${key[Backspace]}" backward-delete-char
[[ -n "${key[Up]}"        ]]  && bindkey  "${key[Up]}"        up-line-or-history
[[ -n "${key[Down]}"      ]]  && bindkey  "${key[Down]}"      down-line-or-history
[[ -n "${key[Left]}"      ]]  && bindkey  "${key[Left]}"      backward-char
[[ -n "${key[Right]}"     ]]  && bindkey  "${key[Right]}"     forward-char
[[ -n "${key[PageUp]}"    ]]  && bindkey  "${key[PageUp]}"    beginning-of-buffer-or-history
[[ -n "${key[PageDown]}"  ]]  && bindkey  "${key[PageDown]}"  end-of-buffer-or-history

#bindkey -v "[5~" backward-word
#bindkey -v "[6~" forward-word

bindkey -v "^P" history-substring-search-up
bindkey -M vicmd "^P" history-substring-search-up
bindkey -v "^N" history-substring-search-down
bindkey -M vicmd "^N" history-substring-search-down

bindkey "." insert-last-word

bindkey -v "^R" history-incremental-pattern-search-backward
bindkey -M isearch "^P" history-incremental-pattern-search-backward
bindkey -M isearch "^N" history-incremental-pattern-search-forward

bindkey -v ' ' magic-space    # also do history expansion on space
bindkey -v '^I' expand-or-complete-prefix
bindkey -v "^A" beginning-of-line
bindkey -v "^E" end-of-line
bindkey -v "^K" kill-line
bindkey -v "^L" clear-screen
bindkey -v "^U" kill-whole-line
bindkey -v "^V" quoted-insert
bindkey -v "^W" backward-kill-word
bindkey -v "^O" push-line # push current command into buffer, then pull back
bindkey -v "^S" push-line # (stash) push current command into buffer, then pull back

# alow for editing of the command line with $EDITOR
# http://zshwiki.org/home/examples/zlewidgets
autoload -U    edit-command-line
zle -N         edit-command-line
bindkey -a 'v' edit-command-line
