#!/usr/bin/env zsh

############## Source pure bash files #################

bash_source() {
    alias shopt=':'
    alias _expand=_bash_expand
    alias _complete=_bash_comp
    #setopt kshglob noshglob braceexpand
    emulate -R sh -c 'BASH_SOURCE=($1) ; source "$@"'
}

have() {
    unset have
    (( ${+commands[$1]} )) && have=yes
}

setenv() { export $1=$2 }

autoload -U bashcompinit
bashcompinit

