#!/usr/bin/env zsh

[ -e ~/.bash_aliases ] && source ~/.bash_aliases
[ -e ~/.zsh_aliases ] && source ~/.zsh_aliases


function qf {
    cmd=$(fc -rnlI -m '[ar]g*' -2 2>/dev/null | head -n1 | sed 's/^rg/rg --vimgrep/')
    [[ -z $cmd ]] && return 1
    vim -q =(eval ${cmd}) -c 'copen'
}

function recompile_init() {
    for init_file in ~/.zsh/conf.d/*.zwc ~/.zsh/*.zwc
    do
        zrecompile -p "$init_file"
    done
}
