#!/usr/bin/env zsh

# NOTE: most stuff for virtualenv wrapper is done through an anitgen plugin

export WORKON_HOME=$HOME/.virtualenvs

export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true

# Use distrubute in virtualenv's
export VIRTUALENV_USE_DISTRIBUTE=1

if [[ "${KERNEL_NAME}" == "Darwin" ]]
then
    export PYTHONIOENCODING="utf-8"
fi
