#!/usr/bin/env zsh

PATH=/usr/local/bin:$PATH
PATH=/usr/local/sbin:$PATH
PATH=$PATH:/var/lib/gems/1.8/bin
PATH=$PATH:$HOME/.gem/ruby/1.8/bin
PATH=$HOME/.cabal/bin:$PATH
PATH=$PATH:.
PATH=$PATH:/opt/local/bin
PATH=$HOME/Dropbox/bin:$PATH
PATH=$HOME/bin:$PATH
PATH=$HOME/src/sage:$PATH
#PATH=$PATH:"/cygdrive/c/Program Files/Git/bin/"
PATH=$HOME/.local/bin:$PATH
PATH=/usr/local/share/python:$PATH
PATH=$PATH:$HOME/.rvm/bin
PATH=$PATH:$HOME/conf/bin

# include junit in java classpath
CLASSPATH=$CLASSPATH:.:/usr/share/java/junit4.jar

#LD_LIBRARY_PATH=$NXJ_HOME/bin
#NXJ_HOME=/home/rwooden/src/lejos_nxj
