#!/usr/bin/env zsh

SESS=zsh
[[ -n "$SSH_TTY" ]] && SESS=ssh

if echo "$OS" | grep -qi "windows"
then
    echo "No multiplex, on windows"

elif which tmux &> /dev/null && ! [[ $SESS == "zsh" && ( "$TERM" =~ "screen" || "$TERM" =~ "tmux" ) ]]
then
    first=$(tmux ls -F '#{session_created} #{session_name}' | sort -n | head -1 | sed 's/^[0-9]* //')

    tmux ls
    echo
    if [[ -n "${first}" ]]
    then
        echo "$ tm # to attach to ${first}"
    else
        echo "$ tm # for new session"
    fi

    tm() {
        if [[ -n "$@" ]]
        then
            tmux "$@"
        elif [[ -n "${first}" ]]
        then
            tmux attach -t "${first}"
        else
            tmux new
        fi
    }
fi
