variables: variables.yml

web_server:
  bind: 127.0.0.1
  port: 3539
  web_ui: yes
  base_url: /flexget


schedules:
  # Run every task once an hour
  - tasks: '*'
    interval:
      minutes: 30

tasks:
  download_rss:
    parsing:
      series: guessit
    priority: 10
    rss: "{? rss.showrss ?}"
    thetvdb_lookup: yes
    accept_all: yes

    set:
      content_filename: '{% if series_name is defined %}{{ series_name }}{% if series_id %} - {{ series_id }}{% endif %}{% if tvdb_ep_name is defined %} - {{ tvdb_ep_name }}{% endif %}{% else %}{{ title }}{% endif %}'
      path: "{% if series_name is defined %}{? paths.sorted ?}/{{ series_name|replace(' ', '.')|lower }}/{% if series_season is defined %}s{{series_season|pad(2)}}{%endif%}{%else%}{? paths.unsorted ?}{%endif%}"
      label: tv

    all_series:
      assume_special: True
      tracking: backfill
      parse_only: yes

    transmission:
      host: localhost
      port: 50150
      username: "{? transmission.user ?}"
      password: "{? transmission.pass ?}"
      main_file_only: yes
      addpaused: no
      magnetization_timeout: 120

  clean:
    clean_transmission:
      host: localhost
      port: 50150
      username: "{? transmission.user ?}"
      password: "{? transmission.pass ?}"
      finished_for: 6 hours

# vim: sw=2 sts=2
