variables: variables.yml

web_server:
  bind: 127.0.0.1
  port: 3539
  web_ui: yes
  base_url: /flexget


schedules:
  # Run every task once an hour
  - tasks: 'download_rss'
    interval:
      minutes: 60
  - tasks: 'download_yt'
    interval:
      minutes: 30

tasks:
  download_yt:
    youtube:
      - 'https://www.youtube.com/playlist?list=PLQSfQGMnHWJVxe28mL7xk0cdh8yAbQdjO'
    accept_all: yes
    download_youtube:
      add_metadata: true
      format: 'best[filesize<?250M][ext=mp4]/best[filesize<?250M]/[filesize<?250M]/worst'
      outtmpl: '/Volumes/External/media/downloads/unsorted/%(title)s [%(id)s].%(ext)s'
  download_rss:
    parsing:
      series: guessit
    priority: 10
    rss: "{? rss.showrss ?}"
    thetvdb_lookup: yes
    accept_all: yes

    set:
      content_filename: '{% if series_name is defined %}{{ series_name }}{% if series_id %} - {{ series_id }}{% endif %}{% else %}{{ title }}{% endif %}'
      path: "{% if series_name is defined %}{? paths.sorted ?}/{{ series_name|replace(' ', '.')|lower }}/{% if series_season is defined %}s{{series_season|pad(2)}}{%endif%}{%else%}{? paths.unsorted ?}{%endif%}"
      label: tv
      main_file_only: yes
      magnetization_timeout: 120
      skip_files:
        - '*.nfo'
        - '*.sfv'
        - '*[sS]ample*'
        - '*.txt'

    all_series:
      assume_special: True
      tracking: backfill
      parse_only: yes

    transmission:
      host: localhost
      port: 50150
      username: "{? transmission.user ?}"
      password: "{? transmission.pass ?}"
      addpaused: no

    clean_transmission:
      host: localhost
      port: 50150
      username: "{? transmission.user ?}"
      password: "{? transmission.pass ?}"
      finished_for: 6 hours

# vim: sw=2 sts=2
