#!/usr/bin/env zsh

##################### Fix some keys ################

bindkey -v "[3~" delete-char
bindkey -v "" backward-delete-char
bindkey -v "[1~" beginning-of-line
bindkey -v "[4~" end-of-line
bindkey -v "[5~" backward-word
bindkey -v "[6~" forward-word

bindkey -v "^N" up-line-or-search
bindkey -v "^P" down-line-or-search
bindkey -v "[A" up-history
bindkey -v "[B" down-history
bindkey -s '^[.' '!$\t'

bindkey -v "^R" history-incremental-search-backward
bindkey -v ' ' magic-space    # also do history expansion on space
bindkey -v '^I' expand-or-complete-prefix
bindkey -v "^A" beginning-of-line
bindkey -v "^E" end-of-line
bindkey -v "^K" kill-line
bindkey -v "^L" clear-screen
bindkey -v "^U" kill-whole-line
bindkey -v "^V" quoted-insert
bindkey -v "^W" backward-kill-word
bindkey -v "^O" push-line # push current command into buffer, then pull back

bindkey -v "^H" run-help
bindkey -v "^h" run-help

# alow for editing of the command line with $EDITOR
# http://zshwiki.org/home/examples/zlewidgets
autoload -U    edit-command-line
zle -N         edit-command-line
bindkey -a 'v' edit-command-line


