#!/usr/bin/env zsh

############## Source pure bash files #################

bash_source() {
    alias shopt=':'
    alias _expand=_bash_expand
    alias _complete=_bash_comp
    emulate -L sh
    setopt kshglob noshglob braceexpand

    source "$@"
}

have() {
    unset have
    (( ${+commands[$1]} )) && have=yes
}

setenv() { export $1=$2 }

autoload -U bashcompinit
bashcompinit

