#!/usr/bin/env zsh

setopt TRANSIENT_RPROMPT

# get host and set color
case "$ZHOST" in
    razz )
        Color=$PR_LIGHT_CYAN
        ;;
    jazz )
        Color=$PR_GREEN
        ;;
    acadia|cherokee|linode )
        Color=$PR_LIGHT_YELLOW
        ;;
    * )
        # red for unknown host
        Color=$PR_LIGHT_RED
        ;;
esac

if [[ `id -u` -eq 0 ]]; then
    Color=$PR_RED  # red text for root
fi

[ -n "$SSH_TTY" ] && psprepend="${PR_RED}ssh-${PR_NO_COLOR}"

# tries to keep the directory name short in the prompt
function getdir
{
    DIR=`pwd | sed -e "s!$HOME!~!"`

    if [ ${#DIR} -gt 20 ]
    then
        CurDir=`echo $DIR | sed -e "s!\([^/]\{1,2\}\)[^/]*/!\1/!g"`
    else
        CurDir=$DIR
    fi

    echo $CurDir
}


windows=`echo $OS | grep -iq 'windows' && echo true || echo false`

function rePrompt
{
    PS1="${psprepend}${Color}$ZHOST:"
    PS1+="${PR_NO_COLOR}${PS1_DIR}${ZLE_COLOR}\$${PR_NO_COLOR} "
    export PS1
}

function setPrompts
{
    export PS1_DIR=`getdir`
    rePrompt

    if ! $windows
    then
        DISABLE_CHPWD=true vcs_info
    fi

    RPROMPT=""
    [[ -n "$PROJECT" ]] && RPROMPT+=' ${PR_RED}(${PR_BLUE}${PROJECT}${PR_RED})'
    [[ -n "${VIRTUALENV_PROMPT}" ]] && RPROMPT+=' ${PR_GREEN}${VIRTUALENV_PROMPT}'
    [[ -n "${vcs_info_msg_0_}" ]] && RPROMPT+=" ${vcs_info_msg_0_}"
    [[ -n "${PR_NO_COLOR}" ]] && RPROMPT+='${PR_NO_COLOR}'
    export RPROMPT
}

precmd_functions+='setPrompts'
