#!/usr/bin/env zsh

# deal with stupid hostnames
hostname=`hostname`
hostname=`echo "$hostname" | sed 's/\.acadiau\.ca//'`

# get host and set color
if [ `id -u` -eq 0 ]; then
    Color=$PR_RED  # red text for root
else
    case "$hostname" in
        razz )
            Color=$PR_LIGHT_CYAN
            ;;
        jazz )
            Color=$PR_GREEN
            ;;
        dyna174* )
            # Acadia computers
            Color=$PR_LIGHT_YELLOW
            ;;
        * )
            # red for unknown host
            Color=$PR_LIGHT_RED
            ;;
    esac
fi

[ -n "$SSH_TTY" ] && psprepend="${PR_RED}ssh-${PR_NO_COLOR}"

# tries to keep the directory name short in the prompt
function getdir
{
    DIR=`pwd | sed -e "s!$HOME!~!"`

    if [ ${#DIR} -gt 20 ]
    then
        CurDir=`echo $DIR | sed -e "s!\([^/]\{1,2\}\)[^/]*/!\1/!g"`
    else
        CurDir=$DIR
    fi

    echo $CurDir
}


function setPrompts
{
    PS1="${psprepend}${Color}$hostname:"
    PS1+="${PR_NO_COLOR}`getdir`${ZLE_COLOR}\$${PR_NO_COLOR} "
    export PS1

    GIT_INFO=$(get_git_prompt_info)

    RPROMPT=""
    [ -n "$PROJECT" ] && RPROMPT+=' ${PR_RED}(${PR_BLUE}${PROJECT}${PR_RED})'
    [ -n "${VIRTUALENV_PROMPT}" ] && RPROMPT+=' ${PR_GREEN}${VIRTUALENV_PROMPT}'
    [ -n "$GIT_INFO" ] && RPROMPT+=" $GIT_INFO"
    [ -n "${PR_NO_COLOR}" ] && RPROMPT+='${PR_NO_COLOR}'
    export RPROMPT
}

precmd_functions+='setPrompts'
