#!/usr/bin/env zsh

setopt prompt_subst

# handle vi NORMAL/INSERT mode change
ZLE_VIMODE="#"
ZLE_COLOR=$PR_NO_COLOR

function zle-line-init zle-keymap-select 
{
    ZLE_VIMODE="${${KEYMAP/vicmd/N}/(main|viins)/I}"
    ZLE_COLOR="${${KEYMAP/vicmd/$PR_BLUE}/(main|viins)/$PR_GREEN}"
    setPrompts
    zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select
