#!/usr/bin/env zsh

setopt prompt_subst

# handle vi NORMAL/INSERT mode change
export ZLE_VIMODE="#"
export ZLE_COLOR=$PR_NO_COLOR

function zle-line-init zle-keymap-select 
{
    export ZLE_VIMODE="${${KEYMAP/vicmd/N}/(main|viins)/I}"
    export ZLE_COLOR="${${KEYMAP/vicmd/$PR_BLUE}/(main|viins)/$PR_GREEN}"
    rePrompt
    zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select
