#!/usr/bin/env zsh

# use the nice "Command not found" feature from ubuntu
[ -e /etc/zsh_command_not_found ] && source /etc/zsh_command_not_found


# track the last executed command _IN THIS SHELL_.
# Can't just use 'history' or 'fc' because they track across all shells.
track_exec() {
    export LAST_EXEC=$2
}

preexec_functions+='track_exec'

# Prints out a failure notice if last command failed
print_failure() {
    ret_code=$?
    if [[ "$ret_code" != 0 && -n "$LAST_EXEC" ]]
    then
        echo -e "\033[1;31m'$LAST_EXEC' Failed ($ret_code)"
    fi
    export LAST_EXEC=
}

precmd_functions+='print_failure'
