#!/usr/bin/env zsh


# Decide whether to set a screen title
function title()
{
    if [[ $TERM == "screen" ]]
    then
        # Use these two for GNU Screen:
        print -nR $'\033k'$1$'\033'\\
        print -nR $'\033]0;'$2$'\a'

    elif [[ $TERM == "xterm" || $TERM == "rxvt" ]]
    then
        # Use this one instead for XTerms:
        print -nR $'\033]0;'$*$'\a'
    fi
}

function zsh-title()
{
    TITLE=""
    PRE=""
    [ -n "$SSH_TTY" ] && PRE+="${ZHOST} - "
    [ -n "$PROJECT" ] && TITLE+="$PROJECT"
    [ -z "$TITLE" ] && TITLE="zsh"
    TITLE=${PRE}${TITLE}
    title "$TITLE"
}

precmd_functions+='zsh-title'
