#!/usr/bin/env zsh


# Decide whether to set a screen title
function title()
{
    if [[ $TERM == "screen" ]]
    then
        # Use these two for GNU Screen:
        print -nR $'\033k'$1$'\033'\\
        print -nR $'\033]0;'$2$'\a'

    elif [[ $TERM == "xterm" || $TERM == "rxvt" ]]
    then
        # Use this one instead for XTerms:
        print -nR $'\033]0;'$*$'\a'
    fi
}

function zsh-title()
{
    title "`[ -n "$SSH_TTY" ] && echo $hostname-`zsh" "$PWD"
}

precmd_functions+='zsh-title'
