#!/usr/bin/env zsh

SESS=zsh

if [[ -n "$SSH_TTY" ]]
then
    screen -ls | sed '1d;N;$!P;$!D;$d;/^$/d'
elif [[ "$TERM" != "screen" ]]
then
    sess=`screen -ls 2>&1 | grep "$SESS"`
    if [[ -n "$sess" ]]
    then
        if echo "$sess" | grep -q 'Multi.*detached'
        then
            screen -x $SESS
        fi
    else
        screen -S $SESS && exit
    fi
fi
