#!/bin/env zsh

# Faster keyboard repeat rate. The defaults available are so slow and it takes ages to delete a lot of text.
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 12
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
defaults write -g ApplePressAndHoldEnabled -bool false

# Show hidden files in finder. I want to see everything.
defaults write com.apple.finder AppleShowAllFiles YES
