[[ -f "$HOME/.zshrc-pre" ]] && source "$HOME/.zshrc-pre"

#zstyle ':completion:*' use-cache on
#autoload -Uz compinit && compinit

[[ -x /opt/homebrew/bin/brew ]] && eval $(/opt/homebrew/bin/brew shellenv)
[[ -x /opt/homebrew/bin/gcc-11 ]] && export CC=/opt/homebrew/bin/gcc-11

{
  # Compile the completion dump to increase startup speed.
  zcompdump="${XDG_CACHE_HOME:-$HOME/.cache}/prezto/zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# pass unmatched globs verbatim to the command, allowing things like `HEAD^` to work
setopt NO_NOMATCH

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Rebind Alt-Dot after prezto breaks it..
bindkey '^[1' digit-argument
bindkey '^[2' digit-argument
bindkey '^[3' digit-argument
bindkey '^[4' digit-argument
bindkey '^[5' digit-argument
bindkey '^[6' digit-argument
bindkey '^[7' digit-argument
bindkey '^[8' digit-argument
bindkey '^[9' digit-argument
bindkey '^[.' insert-last-word
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '<M-b>' backward-word
bindkey '<M-f>' forward-word

# Alt-Comma to copy earlier arguments after Alt-Dot
autoload -U copy-earlier-word
zle -N copy-earlier-word
bindkey '^[,' copy-earlier-word

# Ctrl-O to stash the current line
bindkey '^o' push-line


alias st='git status'
alias ci='git commit'
alias co='git checkout'
alias gd='git diff'
alias gdc='git diff --cached'
alias gmt='git mergetool'
alias br='git branch'
alias show='git show'
alias rb='git rebase'
alias rbc='git rebase --continue'
alias rbi='git rebase -i'

alias pff='git pull --ff-only'
alias pnf='git pull --no-ff'

alias mff='git merge --ff-only'
alias mnf='git merge --no-ff'

alias po='git push origin'
alias pof='git push origin --force-with-lease'
alias gph='git push origin --set-upstream HEAD'

alias ga='git add'
alias gap='git add --patch'

alias gfu='git fetch origin'
alias gfo='git fetch origin'

alias pr='gh pr create --web'

alias rg='rg -S'
alias prl='pr -l'

alias stfu="osascript -e 'set volume output muted true'"
alias flushdns="dscacheutil -flushcache"

alias vw="nvim +VimwikiIndex +'lcd %:p:h'"

alias tm='tmux new-session -A'

function h() {
  if [[ -z $1 ]]; then
    fc -l
    return
  fi

  fc -l 0 | grep "$@"
}

function setup_macos() {
    # Faster keyboard repeat rate. The defaults available are so slow and it takes ages to delete a lot of text.
    defaults write NSGlobalDomain KeyRepeat -int 1
    defaults write NSGlobalDomain InitialKeyRepeat -int 12
    defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
    defaults write -g ApplePressAndHoldEnabled -bool false

    # Show hidden files in finder. I want to see everything.
    defaults write com.apple.finder AppleShowAllFiles YES
}

[[ -f "/opt/homebrew/opt/fzf/shell/key-bindings.zsh" ]] && source "/opt/homebrew/opt/fzf/shell/key-bindings.zsh"

[[ -f "$HOME/.zshrc-post" ]] && source "$HOME/.zshrc-post"

[[ -f /opt/dev/sh/chruby/chruby.sh ]] && { type chruby >/dev/null 2>&1 || chruby () { source /opt/dev/sh/chruby/chruby.sh; chruby "$@"; } }
